import math
print(math.ceil(1.4))
print(math.fabs(-66.43))
print(math.fabs(-7)) 
print(math.factorial(5))
print(math.floor(0.6))
print(math.floor(1.4))
print(math.floor(-5.3))
print(math.floor(22.6))
print(math.floor(10.0))